- name: Copy Grafana
  copy:
    src: "/root/ansible/grafana"
    dest: /home/ubuntu/grafana

- name: Build Grafana image
  command: docker build -t custom-grafana /root/ansible/grafana
  args:
    chdir: /home/ubuntu/grafana

- name: Run Grafana container
  docker_container:
    name: grafana
    image: custom-grafana
    ports:
      - "3000:3000"
    restart_policy: always
